# Implement Feed Forward [Network](https://github.com/ABHISHEKSUBHASHSWAMI)

## Import Numpy Library

In [11]:
import numpy as np


## Define Functions

In [12]:

def activation(z):
  return 1/(1+np.exp(-z))

def loss_function(target,output):               
  #Mean Squared Error
  return (1/len(target))*np.square(target-output)

def forwardpass(x,w1,w2,b1,b2):
  #input to hidden layer
  weighted_sum1=np.dot(x,w1)+b1
  print("Weighted Sum from input layer :\n",weighted_sum1)
  h_in=activation(weighted_sum1)
  #hidden to output layer
  weighted_sum2=np.dot(h_in,w2)+b2
  print("Weighted Sum from hidden layer :\n",weighted_sum2)
  h_out=activation(weighted_sum2)
  return h_out


## Load data

In [13]:

#input data
x=np.array([[0.1, 0.3], [0.7, 0.2], [0.2, 0.4]])

#targets
targets=np.array([[0], [1], [1]])

# Weights and biases for the input layer to hidden layer
w1= np.array([[0.8, 0.1], [0.9, 0.2]])
b1 = np.array([0.1, 0.2])

# Weights and bias for the hidden layer to output layer
w2 = np.array([[0.7], [0.3]])
b2= np.array([0.1])


## Computation

In [14]:

final_output=forwardpass(x,w1,w2,b1,b2)
loss=loss_function(targets,final_output)

print("Input Data :\n",x)
print("Output :\n",final_output)
print("Loss :\n",loss)



Weighted Sum from input layer :
 [[0.45 0.27]
 [0.84 0.31]
 [0.62 0.3 ]]
Weighted Sum from hidden layer :
 [[0.69757534]
 [0.76199123]
 [0.72748574]]
Input Data :
 [[0.1 0.3]
 [0.7 0.2]
 [0.2 0.4]]
Output :
 [[0.66764997]
 [0.6817859 ]
 [0.67425329]]
Loss :
 [[0.1485855 ]
 [0.03375341]
 [0.03537031]]
